#!/usr/bin/env bash
#
# Copyright 2024-2025 The Linux Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
set -eo pipefail

script=${1:-/dev/stdin}
include_dir="$(dirname "$script")/libs"

mkdir -p "$include_dir" 2>/dev/null || include_dir=$(mktemp -d)

INCLUDE_DIR="$include_dir" \
bashpp "$script" | sed '1s,^#!.*$,#!/usr/bin/env bash,'
